import {
  FLAG_AU,
  FLAG_CA,
  FLAG_DE,
  FLAG_ES,
  FLAG_FR,
  FLAG_HK,
  FLAG_IT,
  FLAG_JP,
  FLAG_MX,
  FLAG_TW,
  FLAG_UK,
  FLAG_US,
  FLAG_SG,
  FLAG_NL,
  FLAG_SE,
  FLAG_CN,
} from 'config/images/flags';

export const REGION_INFO = {
  US: {
    country: 'United States',
    group: 'Americas',
    code: 'us',
    language: 'en-us',
    image: FLAG_US,
  },
  CA: {
    country: 'Canada',
    group: 'Americas',
    code: 'ca',
    language: 'en-ca',
    image: FLAG_CA,
  },
  CN: {
    country: '中国',
    group: 'Americas',
    code: 'cn',
    language: 'zh-cn',
    image: FLAG_CN,
  },
  MX: {
    country: 'México',
    group: 'Americas',
    code: 'mx',
    language: 'es-mx',
    image: FLAG_MX,
  },
  UK: {
    country: 'United Kingdom',
    group: 'Europe',
    code: 'uk',
    language: 'en-gb',
    image: FLAG_UK,
  },
  DE: {
    country: 'Deutschland',
    group: 'Europe',
    code: 'de',
    language: 'de-de',
    image: FLAG_DE,
  },
  FR: {
    country: 'France',
    group: 'Europe',
    code: 'fr',
    language: 'fr-fr',
    image: FLAG_FR,
  },
  IT: {
    country: 'Italia',
    group: 'Europe',
    code: 'it',
    language: 'it-it',
    image: FLAG_IT,
  },
  ES: {
    country: 'Espana',
    group: 'Europe',
    code: 'es',
    language: 'es-es',
    image: FLAG_ES,
  },
  SE: {
    country: 'Sverige',
    group: 'Europe',
    code: 'se',
    language: 'sv-se',
    image: FLAG_SE,
  },
  NL: {
    country: 'Nederland',
    group: 'Europe',
    code: 'nl',
    language: 'nl-nl',
    image: FLAG_NL,
  },
  AU: {
    country: 'Australia',
    group: 'Asia-Pacific',
    code: 'au',
    language: 'en-au',
    image: FLAG_AU,
  },
  HK: {
    country: '香港',
    group: 'Asia-Pacific',
    code: 'hk',
    language: 'zh-hk',
    image: FLAG_HK,
  },
  TW: {
    country: '臺灣',
    group: 'Asia-Pacific',
    code: 'tw',
    language: 'zh-tw',
    image: FLAG_TW,
  },
  JP: {
    country: '日本',
    group: 'Asia-Pacific',
    code: 'jp',
    language: 'ja-jp',
    image: FLAG_JP,
  },
  SG: {
    country: 'Singapore',
    group: 'Asia-Pacific',
    code: 'sg',
    language: 'en-sg',
    image: FLAG_SG,
  },
};

const regionList = ['us', 'ca', 'de', 'uk', 'fr'];

export const PATHS = regionList.map((region) => ({ params: { region } }));
