import {
  FLAG_AU,
  FLAG_CA,
  FLAG_DE,
  FLAG_ES,
  FLAG_FR,
  FLAG_HK,
  FLAG_IT,
  FLAG_JP,
  FLAG_MX,
  FLAG_TW,
  FLAG_UK,
  FLAG_US,
  FLAG_SG,
  FLAG_NL,
  FLAG_SE,
  FLAG_CN,
} from 'config/images/flags';

export const REGION_INFO = {
  US: {
    country: 'United States',
    group: 'Americas',
    code: 'us',
    language: 'en-US',
    image: FLAG_US,
  },
  CA: {
    country: 'Canada',
    group: 'Americas',
    code: 'ca',
    language: 'en-CA',
    image: FLAG_CA,
  },
  CN: {
    country: '中国',
    group: 'Americas',
    code: 'cn',
    language: 'zh-CN',
    image: FLAG_CN,
  },
  MX: {
    country: 'México',
    group: 'Americas',
    code: 'mx',
    language: 'es-MX',
    image: FLAG_MX,
  },
  UK: {
    country: 'United Kingdom',
    group: 'Europe',
    code: 'uk',
    language: 'en-GB',
    image: FLAG_UK,
  },
  DE: {
    country: 'Deutschland',
    group: 'Europe',
    code: 'de',
    language: 'de-DE',
    image: FLAG_DE,
  },
  FR: {
    country: 'France',
    group: 'Europe',
    code: 'fr',
    language: 'fr-FR',
    image: FLAG_FR,
  },
  IT: {
    country: 'Italia',
    group: 'Europe',
    code: 'it',
    language: 'it-IT',
    image: FLAG_IT,
  },
  ES: {
    country: 'Espana',
    group: 'Europe',
    code: 'es',
    language: 'es-ES',
    image: FLAG_ES,
  },
  SE: {
    country: 'Sverige',
    group: 'Europe',
    code: 'se',
    language: 'sv-SE',
    image: FLAG_SE,
  },
  NL: {
    country: 'Nederland',
    group: 'Europe',
    code: 'nl',
    language: 'nl-NL',
    image: FLAG_NL,
  },
  AU: {
    country: 'Australia',
    group: 'Asia-Pacific',
    code: 'au',
    language: 'en-AU',
    image: FLAG_AU,
  },
  HK: {
    country: '香港',
    group: 'Asia-Pacific',
    code: 'hk',
    language: 'zh-HK',
    image: FLAG_HK,
  },
  TW: {
    country: '臺灣',
    group: 'Asia-Pacific',
    code: 'tw',
    language: 'zh-TW',
    image: FLAG_TW,
  },
  JP: {
    country: '日本',
    group: 'Asia-Pacific',
    code: 'jp',
    language: 'ja',
    image: FLAG_JP,
  },
  SG: {
    country: 'Singapore',
    group: 'Asia-Pacific',
    code: 'sg',
    language: 'en-SG',
    image: FLAG_SG,
  },
};
