const productSlideStyle = (theme) => ({
  root: {
    backgroundColor: theme.palette.white,
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column',
    },
  },
  center: {
    backgroundColor: theme.palette.white,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  indicatorContainerLeft: {
    backgroundColor: theme.palette.white,
    width: 'auto',
    height: 'auto',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexDirection: 'column',
  },
  indicatorContainerRight: {
    backgroundColor: theme.palette.white,
    width: 'auto',
    height: 'auto',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  indicatorContainer: {
    width: '100%',
    // height: '100%',
  },
  carouselContainer: {
    backgroundColor: theme.palette.white,
    top: '100px',
    width: '100%',
    height: 'auto',
  },
  button: {
    padding: '0px',
  },
  buttonContainer: {
    backgroundColor: theme.palette.white,
    margin: '10px',
    width: '62px',
    height: '62px',
  },
  buttonIcon: {
    width: '60px',
    height: '60px',
  },
  slide: {
    backgroundColor: theme.palette.white,
    padding: '30px',
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    maxHeight: '100%',
    maxWidth: '100%',
  },
  slideImage: {
    backgroundColor: theme.palette.white,
    width: '100%',
    height: '100%',
    maxHeight: '100%',
    maxWidth: '100%',
  },
  slideVideo: {
    backgroundColor: theme.palette.white,
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 'auto',
    width: '100%',
    height: '100%',
  },
  arrow: {
    position: 'absolute',
    zIndex: 2,
    top: 'calc(50% - 15px)',
    width: 30,
    height: 30,
    cursor: 'pointer',
    backgroundColor: theme.palette.yellow,
    padding: '0px',
    color: '#fff',
    '&,&:hover,&:focus': {
      backgroundColor: theme.palette.yellow,
    },
  },
});

export default productSlideStyle;
